mlflow:
  path: ${oc.env:dzc_ALL_CCFRSCRATCH}/cp/mlruns
  run_name: pafnucy_rot_v1

io:
  input_dir: ${oc.env:$dzc_ALL_CCFRWORK}/deep_learning/pafnucy/data/CoG_12 # contains train, val and test dataset as h5py files
  log_dir: ./log
  output_prefix: results/CoG_12/replicate_1/output   # TODO
  model_path: ${oc.env:dzc_ALL_CCFRSCRATCH}/cp/models

data:
  grid_spacing: 1.0 # distance between grid points in angstrom
  max_dist: 12 # max distance from complex center
  replicate: 1 # TODO ??

network:
  conv_kernel_size: 5 # patch size for convolutional layers
  pool_kernel_size: 2 # patch size for pooling layers
  conv_channels: [ 19, 64, 128, 256 ] # number of filters in convolutional layers
  dense_sizes: [ 16384, 1000, 500, 200 ] # number of neurons in dense layers
  # setup [MS]
  input_spatial_dim: 25
  conv_dims: [ 19, 64, 256, 1024 ]
  drop_p: 0.5 # keep probability for dropout

training:
  learning_rate: 1e-5 # learning rate
  batch_size: 20 # batch size
  num_epochs: 2 # number of epochs
  patience: 40 # early stopping
  #checkpoint_max_to_keep: 10 # number of checkpoints to keep
  weight_decay: 0.001 # lambda for weight decay

experiment_name: pafnucy_rotation


