hydra: #prevent hydra log from filing home
  run:
    dir: ${oc.env:luh_CCFRWORK}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

experiment: # mlflow data
  name: expe0
  run: debug2
  path: ${oc.env:luh_CCFRSCRATCH}/mlruns
  by_complex: true # if false, it is by simulation
  model_path: ${oc.env:luh_CCFRSCRATCH}/models/cnn-lstm/

model:
  architecture: single_cnn    # valid options: single_cnn, soon multi_cnn, single_dense, multi_dense

io:
  by_complex_dir: ${oc.env:luh_CCFRWORK}/version4D/inputs_v4/by_complex
  by_sim_dir: ${oc.env:luh_CCFRWORK}/version4D/inputs_v4/by_sim
  train_samples: training_samples.txt
  val_samples: validation_samples.txt
  test_samples: test_samples.txt
  affinities:
    - ${oc.env:luh_ALL_CCFRWORK}/version4D/inputs/affinities/INDEX_general_PL_data.2019
    - ${oc.env:luh_ALL_CCFRWORK}/version4D/inputs/affinities/INDEX_refined_data.2019
  train_dir: ${oc.env:luh_ALL_CCFRWORK}/deep_learning/pafnucy/data/4D_data_v4/training_set
  val_dir: ${oc.env:luh_ALL_CCFRWORK}/deep_learning/pafnucy/data/4D_data_v4/validation_set
  test_dir: ${oc.env:luh_ALL_CCFRWORK}/deep_learning/pafnucy/data/4D_data_v4/test_set

data_setup:
  grid_spacing: 1.0  # distance between grid points in angstrom
  max_dist: 12 # max distance from complex center # TODO still useful 
  partial_charges:  # previously computed on all simulations from train dataset
    mean: -0.19436523
    std: 0.65582558
  frames: 50  # 50 is the maximum, less mean that #frames will be randomly chosen
  keep_frames_in_order: true
  features: 19

training:
  learning_rate: 1e-4 # learning rate
  weight_decay: 0.0001 # lambda for weight decay
  batch_size: 16 # batch size
  num_epochs: 300 # max number of epochs
  patience: 20 # early stopping
  warmup_epochs: 10

network:
  pretrained_path:
  mean_test:
  sim_test:

debug: false


